"""init

Revision ID: 3dc66265e745
Revises: 
Create Date: 2022-05-16 16:44:38.822520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3dc66265e745"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_accesstoken_created_at", table_name="accesstoken")
    op.drop_table("accesstoken")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_job_id", table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("company", sa.VARCHAR(), nullable=False),
        sa.Column("company_url", sa.VARCHAR(), nullable=True),
        sa.Column("location", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("date_posted", sa.DATETIME(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("owner_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_id", "job", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("email", sa.VARCHAR(length=320), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(), nullable=False),
        sa.Column("last_name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.create_table(
        "accesstoken",
        sa.Column("token", sa.VARCHAR(length=43), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index("ix_accesstoken_created_at", "accesstoken", ["created_at"], unique=False)
    # ### end Alembic commands ###
