"""First Commit

Revision ID: 7a22213428f9
Revises: 3dc66265e745
Create Date: 2022-05-17 19:08:35.303495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a22213428f9'
down_revision = '3dc66265e745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
